spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:~/odiga;MODE=MYSQL
  jpa:
    show-sql: true
    properties:
        hibernate:
          format_sql: true
        ddl-auto: none
  flyway:
    enabled: false

  data:
    redis:
      host: 127.0.7.1
      port: 6379
