# application.yml
spring:
  profiles:
    group:
      local:
        - cloud
        - localjwt
      prod:
        - cloud
      test:
        - localjwt

    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
