spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:~/odiga;MODE=MYSQL
  jpa:
    show-sql: true
    properties:
        hibernate:
          format_sql: true
        ddl-auto: none
  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    header: Authorization
    issuer: odiga
    client-secret: mock
    expiry-seconds: 2592000
    secret: mock

cloud:
  aws:
    credentials:
      accessKey: mock
      secretKey: mock
    s3:
      bucket: mock
    region:
      static: ap-northeast-2
    stack:
      auto: false
